apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timeserver-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
    app: timeserver
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /timeserver
            pathType: Prefix
            backend:
              service:
                name: timeserver-service
                port:
                  number: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: timeserver-service
  labels:
    app: timeserver
spec:
  type: LoadBalancer
  selector:
    app: timeserver
    component: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeserver-deployment
  labels:
    app: timeserver
spec:
  replicas: 8
  selector:
    matchLabels:
      app: timeserver
      component: api
  template:
    metadata:
      labels:
        app: timeserver
        component: api
    spec:
      containers:
        - name: timeserver
          image: milldam/timeserver:1.0
          ports:
            - containerPort: 3000
---
